name: Update README Status

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'        # the bot’s README commit won't retrigger the job
  schedule:
    - cron: '*/30 * * * *' # refresh every 30 minutes
  workflow_dispatch:        # manual "Run workflow" button

concurrency:
  group: readme-status
  cancel-in-progress: true



permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update README status
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: node scripts/update-readme.mjs

      - name: Commit README update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update README status"
          file_pattern: README.md
